### ISSUE TITLE
Upload checklist json from UI

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#323]
Currently, there is no way to upload checklists from the UI. There is a [story](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/42) that provides the right UI to upload checklists. However, we are live right now, and there is not enough time to build a UI like this. 

In order to fix this, we will currently provide a text box on the UI to upload the checklist json. A typical structure of the checklist json is provided here - https://github.com/avniproject/calcutta-kids/blob/master/child/checklist.json

Right now checklist is not directly linked to a program and we use checklist rule to use it for any program, so it'll be a separate screen in App designer.

### Acceptance criteria

- [x] Upload is available through the URL POST /checklistDetail
- [x] Verify that the string uploaded is a valid JSON
- [x] Verify that the concept uuids provided are valid
- [x] Check if there are error messages from the server that are not clear. 

### Out of scope

- [ ] Json schema validation

**Comment by vindeolal** [comment]
Documentation link : https://avni.readme.io/docs/upload-checklist#
