### ISSUE TITLE
Giving permission for view checklist gives error

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#432]
**Describe the bug**
Giving permission for "view checklist" for a user group gives error.

**To Reproduce**
1. Create a new user group
2. Give permission to View subject, view enrolment details. When you give permission for "view checklist" you get an error
3. The error message title is not the best.

**Screenshots**
![image](https://user-images.githubusercontent.com/105867/85851929-490d2b80-b7cd-11ea-9182-81a3697adb39.png)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [x] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [x] Yes
  - [ ] No

Test Cases
- [x] User should be able to set checklist related privileges.
- [x] Other privileges should work as earlier.
- [x] Choose any edit privilege (say edit encounter), this automatically gives the privilege of view encounter. Check in DB ```group_privilege``` table should have these two entries with allowed true. Now from the web revoke view encounter privilege, this should revoke both the privileges in DB also. Earlier this was creating a new entry in DB.
- [x] Privilege sync should work as earlier in the mobile client.

**Comment by vindeolal** [comment]
Apart from the above-mentioned bug, there was one more bug. If you revoke any dependent privilege then a new entry was getting created in DB instead of updating the old entry. For example, say you have edit and view privilege of enrolment. Now if you revoke view enrolment privilege, it automatically revokes edit enrolment privilege, but in DB a new entry gets created, without updating the older one.
