### ISSUE TITLE
Form Navigation incorrect and wrong step number

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#525]
Org: Calcutta kids
Child -> Birth Visit -> ﻿After going to the summary page when I press previous button it takes me to the 1st page instead of 2nd page(There are only 2 groups). Also when I come to last page again it shows counter as 4/3.

Org: TestJoy
SR Screen is shown as step 3/2 for a registration form with just one page.

**Comment by 1t5j0y** [comment]
Scenarios 
- [ ] Empty form element group just before summary page (incorrect behaviours - step count goes beyond total number)
- [ ] Empty form element group just before summary page (going previous from summary page takes you 2 steps previous)
- [ ] Non empty form element group after empty form element group (incorrect behaviour - non empty form element group is skipped while going next. It is only shown when you use previous button.)

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Pre bug bash org
Household reg form - skipped FEG 'Contact'. This FEG is just before the summary page. 
when the registration form is filled, it shows the FEG (it does not show the FE though).
-

**Comment by hithacker** [comment]
Going to refactor form navigation logic to the reducer. 
**Tasks**
1. Move the summary page out of FormWizard and make it a standalone page. 
2. Move the logic of getting the current group to FormWizardReducer.
3. Move the logic of getting the next and previous group to FormWizardReducer.
4. Add the logic to return the redirect flag for moving to the last page(summary) to the FormWizardReducer. Subscribe to this state in the FormWizard and redirect to the last page.

**Comment by hithacker** [comment]
The above approach of wanting to only move load, next, prev logic to a new reducer will not work because other logic like updating the element and initializing the page is split into workflow specific reducers. 
So have decided to move next, prev, onLoad also to

**Comment by hithacker** [comment]
### What else is different in avni-webapp and avni-client code bases wizard part?
1. We are doing the dispatching of different methods based on different type inside of a component FormElementGroup in the avni-client codebase but in avni-webapp we have a single updateObs method and that does the if-elses required. Also, the common code to update the obs and validate is put into a common place(ObservationHolderActions) in avni-client, but it's duplicated in each obsWorker function we have for(penc, penc cancel, enc, enc cancel, enl, enl exit, and registration). E.g. See updateEncounterObsWorker and updateCancelEncounterObsWorker functions in encounterSaga.js file.
2. For non person registration page, we are not showing the first group along with the static page in webapp. To do, this we will need to move out next and previous buttons from FormWizard class that we have. Also once you remove the next and previous button from the component it's pretty much the same as a FormElementGroup so it should be renamed. We will also have to use WizardButtons(avni-client) like abstraction in each form page. Basically, we will compose the FormElementGroup and WizardButtons the same way we do in the avni-client code.
3. Summary page and other pages working from the same component - FormWizard. In the android app we have Summary page as a separate page that users navigate to once they fill the last group and press next. In the webapp, the Summary component is embedded in FormWizard component. In the webapp though, it would not be nice to change the page url when users go to the summary page so the current approach seems fine.
4. AbstractDataEntryState. In the avni-client code, we have uses abstract class patten for the state management of different forms(penc, penc cancel etc) because even though the main part of the logic is same, there will be some differences between the forms, like using cancel observations or main observations etc. This also makes it easy to add code for a new type of form as you just need to override the Abstract class and implement the differences. This is not done in the webapp code. In webapp code we currently are not using this pattern. We are managing this by passing different state to the common components based on the form type E.g. see ProgramEnrolmentForm.js and ProgramExitEnrolmentForm.js. Also we have put the common code for managing on_load, next, and previous actions in a util module named commonFormUtils.js so we don't have to duplicate this logic. We may want to consider using the similar pattern as avni-client but doing this will require quite a bit of refactoring and testing.
