### ISSUE TITLE
Media Viewer

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#904]
There is a requirement where client admin person should be able to browse through the images and download selected images in a zip file. 

For this, a new web-interface to be introduced in Avni platform which will allow
- Providing a filter criteria covering attributes and location hierarchy
- Browsing image one by one using next and previous
- Downloading a zip file containing all the images matching the filter criteria

```[tasklist]
### Stories
- [ ] avniproject/avni-etl#43
- [x] avniproject/avni-etl#53
- [x] avniproject/avni-client#977
- [x] avniproject/avni-media#62
- [x] avniproject/avni-etl#44
- [x] avniproject/avni-webapp#942
- [x] avniproject/avni-media#64
- [x] avniproject/avni-media#67
- [x] avniproject/avni-media#43
- [x] avniproject/avni-media#65
- [x] avniproject/avni-media#14
- [x] avniproject/avni-media#53
- [x] avniproject/avni-media#66
- [x] avniproject/avni-etl#32
- [x] avniproject/avni-media#60
- [x] avniproject/avni-media#38
- [x] avniproject/avni-media#44
- [x] avniproject/avni-media#37
- [x] avniproject/avni-media#51
- [x] avniproject/avni-webapp#906
- [x] avniproject/avni-etl#45
- [x] avniproject/avni-webapp#956
- [x] avniproject/avni-webapp#924
- [x] avniproject/avni-media#16
- [x] avniproject/avni-media#34
- [x] avniproject/avni-webapp#905
- [x] avniproject/avni-etl#42
- [x] avniproject/avni-media#30
- [x] avniproject/avni-media#13
- [x] avniproject/avni-webapp#908
- [x] avniproject/avni-etl#40
- [x] avniproject/avni-webapp#943
- [x] avniproject/avni-etl#34
- [x] avniproject/avni-etl#30
- [x] avniproject/avni-webapp#923
- [x] avniproject/avni-webapp#927
- [ ] avniproject/avni-server#521
- [x] avniproject/avni-webapp#960
- [ ] avniproject/avni-webapp#945
- [ ] avniproject/avni-webapp#909
- [x] avniproject/avni-webapp#941
- [ ] avniproject/avni-webapp#910
- [x] avniproject/avni-media#99
```

**Comment by vinayvenu** [comment]
Logic for thumbnail generation needs to be fixed
Naming/description of zip files
directory structure of zip files
concept search filter
Name of image
UI changes
Prod infra requirements analysis and deployment (including CI)
Logging analysis in media viewer
Ping check and emails (Freshping)
Date format needs to be corrected on carousel and in Available Downloads
Configurable number of images per page
